CREATE TABLE SYS_ID (
    StoreNo    VARCHAR(10) NOT NULL
    NAME       VARCHAR(50) NOT NULL,
    SEQ        BIGINT,
    RESETMODE  VARCHAR(10) not null,
    LASTDATE   DATE,
    CONSTRAINT PK_SYS_ID PRIMARY KEY (StoreNo, NAME, RESETMODE)	
);
